'pull_request_title': 'chore(localize): updated translation from Crowdin'
'pull_request_labels': ['crowdin']

files:
  - source: /locales/en/*.json
    translation: /locales/%locale%/%original_file_name%
