FROM node:24-alpine

# Install Java (Required for Firebase Emulators)
RUN apk add --no-cache openjdk21-jre bash

# Install Firebase CLI
RUN npm install -g firebase-tools

WORKDIR /app

CMD ["firebase", "emulators:start", "--only", "auth", "--project", "organized-local"]