name: CodeQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 12 * * 4'

permissions: read-all

jobs:
  codeql:
    name: Code QL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository for code analysis
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Initialize CodeQL
        uses: github/codeql-action/init@9fdb3e49720b44c48891d036bb502feb25684276
        with:
          languages: javascript
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@9fdb3e49720b44c48891d036bb502feb25684276
