name: CD

on:
  workflow_dispatch:

permissions: read-all

jobs:
  deploy:
    name: Deploy API to Production
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.ref == 'refs/heads/prod' }}
    environment:
      name: Prod.env
      url: https://api.sws2apps.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          ref: prod
          persist-credentials: false

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@8e58d20d0f6c8773181f43eb74d6a05e3099571d
        with:
          semantic_version: 19.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy API to Heroku
        if: ${{ steps.semantic.outputs.new_release_published == 'true' }}
        uses: akhileshns/heroku-deploy@9fd0f9faae4aa93a38d6f5e25b9128589f1371b0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: sws2apps
          heroku_email: ${{secrets.HEROKU_EMAIL}}
