name: NodeJSScan

on:
  push:
    branches: [main, beta, alpha]
  pull_request:
    branches: [main, beta, alpha]
  schedule:
    - cron: '0 12 * * 4'

permissions: read-all

jobs:
  nodejsscan:
    name: NodeJS Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout the code

      - name: Upload njsscan report
        with:
          sarif_file: results.sarif
