name: CD-Redeploy

on:
  workflow_dispatch:

permissions: read-all

jobs:
  redeploy_dev:
    name: Redeploy API to Render
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.ref == 'refs/heads/main' }}
    environment:
      name: Prod.env
      url: https://sws2apps-api.onrender.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: main
          persist-credentials: false

      - name: Render Deployment
        uses: sws2apps/render-deployment@90a5d9c22cdc4c78be3c2dd926ca9b84e2d7d70c
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
